#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GdsVideoBackend;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/PartialViews/_LeftMenuPartial.cshtml")]
    public partial class _Views_PartialViews__LeftMenuPartial_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_PartialViews__LeftMenuPartial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<ul");

WriteLiteral(" class=\"nav metismenu\"");

WriteLiteral(" id=\"side-menu\"");

WriteLiteral(">\r\n    <li");

WriteLiteral(" class=\"nav-header\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"dropdown profile-element\"");

WriteLiteral(">\r\n            <span>\r\n                <img");

WriteLiteral(" alt=\"image\"");

WriteLiteral(" class=\"img-circle\"");

WriteLiteral(" src=\"img/profile_small.jpg\"");

WriteLiteral(">\r\n            </span>\r\n            <a");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"clear\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"block m-t-xs\"");

WriteLiteral(">\r\n                        <strong");

WriteLiteral(" class=\"font-bold\"");

WriteLiteral(">David Williams</strong>\r\n                    </span> <span");

WriteLiteral(" class=\"text-muted text-xs block\"");

WriteLiteral(">Art Director <b");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></b></span>\r\n                </span>\r\n            </a>\r\n            <ul");

WriteLiteral(" class=\"dropdown-menu animated fadeInRight m-t-xs\"");

WriteLiteral(">\r\n                <li><a");

WriteLiteral(" href=\"profile.html\"");

WriteLiteral(">Profile</a></li>\r\n                <li><a");

WriteLiteral(" href=\"contacts.html\"");

WriteLiteral(">Contacts</a></li>\r\n                <li><a");

WriteLiteral(" href=\"mailbox.html\"");

WriteLiteral(">Mailbox</a></li>\r\n                <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                <li><a");

WriteLiteral(" href=\"login.html\"");

WriteLiteral(">Logout</a></li>\r\n            </ul>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"logo-element\"");

WriteLiteral(">\r\n            IN+\r\n        </div>\r\n    </li>\r\n    \r\n    <li>\r\n        <a");

WriteLiteral(" href=\"layouts.html\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-diamond\"");

WriteLiteral("></i> <span");

WriteLiteral(" class=\"nav-label\"");

WriteLiteral(">Layouts</span></a>\r\n    </li>\r\n    \r\n    <li>\r\n        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-edit\"");

WriteLiteral("></i> <span");

WriteLiteral(" class=\"nav-label\"");

WriteLiteral(">Forms</span><span");

WriteLiteral(" class=\"fa arrow\"");

WriteLiteral("></span></a>\r\n        <ul");

WriteLiteral(" class=\"nav nav-second-level collapse\"");

WriteLiteral(">\r\n            <li><a");

WriteLiteral(" href=\"form_basic.html\"");

WriteLiteral(">Basic form</a></li>\r\n            <li><a");

WriteLiteral(" href=\"form_advanced.html\"");

WriteLiteral(">Advanced Plugins</a></li>\r\n            <li><a");

WriteLiteral(" href=\"form_wizard.html\"");

WriteLiteral(">Wizard</a></li>\r\n            <li><a");

WriteLiteral(" href=\"form_file_upload.html\"");

WriteLiteral(">File Upload</a></li>\r\n            <li><a");

WriteLiteral(" href=\"form_editors.html\"");

WriteLiteral(">Text Editor</a></li>\r\n        </ul>\r\n    </li>\r\n</ul>");

        }
    }
}
#pragma warning restore 1591
