#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GiaoDucSomVideo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Course/Index.cshtml")]
    public partial class _Views_Course_Index_cshtml : System.Web.Mvc.WebViewPage<GiaoDucSomVideo.Models.CourseDetailViewModel>
    {
        public _Views_Course_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Course\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"container-wrapper\"");

WriteLiteral(" style=\"overflow: hidden;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"bg-detail no-padding no-margin\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"banner\"");

WriteLiteral(">\r\n        </div>\r\n        <!-- + Get user and course information -->\r\n        <i" +
"nput");

WriteLiteral(" class=\"course_id\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 392), Tuple.Create("\"", 415)
            
            #line 12 "..\..\Views\Course\Index.cshtml"
, Tuple.Create(Tuple.Create("", 400), Tuple.Create<System.Object, System.Int32>(Model.CourseId
            
            #line default
            #line hidden
, 400), false)
);

WriteLiteral(">\r\n        <input");

WriteLiteral(" class=\"course_name\"");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("value", Tuple.Create(" value=\"", 467), Tuple.Create("\"", 492)
            
            #line 13 "..\..\Views\Course\Index.cshtml"
, Tuple.Create(Tuple.Create("", 475), Tuple.Create<System.Object, System.Int32>(Model.CourseName
            
            #line default
            #line hidden
, 475), false)
);

WriteLiteral(">\r\n        <!-- + Report modal -->\r\n        <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"complete-dialog\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(">×</button>\r\n                        <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(">Báo lỗi</h4>\r\n                    </div>\r\n                    <!-- %hr{:style =>" +
" \"margin-top: 15px; margin-bottom: 15px;\"} -->\r\n                    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                        <form>\r\n                            <textarea");

WriteLiteral(" class=\"txt-report-content\"");

WriteLiteral(" placeholder=\"Nội dung báo lỗi\"");

WriteLiteral(" rows=\"5\"");

WriteLiteral(" style=\"border: 1px solid #ccc; height: 100%; width: 100%; padding : 5px 15px\"");

WriteLiteral("></textarea>\r\n                        </form>\r\n                    </div>\r\n      " +
"              <!-- %hr{:style => \"margin-top: 10px; margin-bottom: 10px;\"} -->\r\n" +
"                    <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(" style=\"border: 0px solid #fff\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" class=\"btn btn-primary btn-submit-report\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Gửi</button>\r\n                        <button");

WriteLiteral(" class=\"btn\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Đóng</button>\r\n                    </div>\r\n                </div>\r\n            <" +
"/div>\r\n        </div>\r\n        <!-- Menu fix -->\r\n        <div");

WriteLiteral(" class=\"row no-margin menu-fixed\"");

WriteLiteral(" style=\"border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color" +
": rgb(204, 204, 204); display: none;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n            </div>\r\n            <ul");

WriteLiteral(" class=\"menu-fixed-right\"");

WriteLiteral(">\r\n                <li>\r\n                    <a");

WriteLiteral(" class=\"btn btn-raised btn-lg buy-button\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" style=\"padding:5px 15px\"");

WriteLiteral(">\r\n                        Mua khóa học\r\n                    </a>\r\n              " +
"  </li>\r\n                <li>\r\n                    <h3");

WriteLiteral(" class=\"course-price-text no-margin bold\"");

WriteLiteral(" style=\"margin: 0; padding-top: 10px\"");

WriteLiteral(">599,000đ</h3>\r\n                </li>\r\n            </ul>\r\n        </div>\r\n       " +
" <!-- + Detail content -->\r\n        <div");

WriteLiteral(" class=\"detail\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"detail-top\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"detail-top-content\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"breadcrumb or-crumb\"");

WriteLiteral(">\r\n                        <li>\r\n                            <a");

WriteLiteral(" href=\"https://edumall.vn/\"");

WriteLiteral(" style=\"color: black;\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-home\"");

WriteLiteral("></i>\r\n                            </a>\r\n                        </li>\r\n         " +
"               <li>");

            
            #line 75 "..\..\Views\Course\Index.cshtml"
                       Write(Model.CategoryName);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    </ul>\r\n                    <h1");

WriteLiteral(" class=\"course-title\"");

WriteLiteral(">");

            
            #line 77 "..\..\Views\Course\Index.cshtml"
                                        Write(Model.CourseName);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n                    <div");

WriteLiteral(" class=\"sub-title\"");

WriteLiteral(">");

            
            #line 78 "..\..\Views\Course\Index.cshtml"
                                      Write(Model.CourseSubTitle);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div");

WriteLiteral(" class=\"course-rating\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"course-rating-point\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(" id=\"percent-rating\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-star rated\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-star rated\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-star rated\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-star rated\"");

WriteLiteral("></i>\r\n                                <span");

WriteLiteral(" class=\"rating-percent\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-star\"");

WriteLiteral("></i>\r\n                                    <i");

WriteLiteral(" class=\"fa fa-star percent\"");

WriteLiteral(" style=\"width: 79.99999999999999%\"");

WriteLiteral("></i>\r\n                                </span>\r\n                            </div" +
">\r\n                        </div>\r\n                    </div>\r\n                 " +
"   <div");

WriteLiteral(" class=\"course-author\"");

WriteLiteral(">\r\n                        Giảng dạy bởi\r\n                        <a");

WriteLiteral(" class=\"link-text normal-text\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" style=\"cursor: default\"");

WriteLiteral(">Tuan Linh</a>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"course-detail\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"course-player\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"video-container no-controls\"");

WriteLiteral(">\r\n                                <img");

WriteLiteral(" style=\"width: 100%; height: 100%\"");

WriteAttribute("src", Tuple.Create(" src=\"", 5310), Tuple.Create("\"", 5376)
, Tuple.Create(Tuple.Create("", 5316), Tuple.Create("data:image/", 5316), true)
            
            #line 100 "..\..\Views\Course\Index.cshtml"
       , Tuple.Create(Tuple.Create("", 5327), Tuple.Create<System.Object, System.Int32>(Model.MimeTypeImage
            
            #line default
            #line hidden
, 5327), false)
, Tuple.Create(Tuple.Create("", 5347), Tuple.Create(";base64,", 5347), true)
            
            #line 100 "..\..\Views\Course\Index.cshtml"
                                   , Tuple.Create(Tuple.Create("", 5355), Tuple.Create<System.Object, System.Int32>(Model.ThumbnailImage
            
            #line default
            #line hidden
, 5355), false)
);

WriteLiteral(" alt=\"Thumbnail tu 570\"");

WriteLiteral(">\r\n                            </div>\r\n                        </div>\r\n          " +
"              <div");

WriteLiteral(" class=\"course-detail-bottom\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"course-detail-bottom-left\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"course-price\"");

WriteLiteral(">\r\n                                    <h3");

WriteLiteral(" class=\"course-price-text no-margin bold\"");

WriteLiteral(">");

            
            #line 106 "..\..\Views\Course\Index.cshtml"
                                                                             Write(Model.Price);

            
            #line default
            #line hidden
WriteLiteral("đ</h3>\r\n                                </div>\r\n                                <" +
"div");

WriteLiteral(" class=\"course-purchase\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"purchase-submit\"");

WriteLiteral(">\r\n                                        <a");

WriteLiteral(" class=\"btn btn-raised btn-lg buy-button\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                            Mua khóa học\r\n                    " +
"                    </a>\r\n                                    </div>\r\n          " +
"                          <div");

WriteLiteral(" class=\"sale-submit\"");

WriteLiteral(">\r\n                                        ");

WriteLiteral("\r\n                                        ");

WriteLiteral("\r\n                                    </div>\r\n                                   " +
" <div");

WriteLiteral(" class=\"report\"");

WriteLiteral(">\r\n                                        ");

WriteLiteral("\r\n                                    </div>\r\n                                </d" +
"iv>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"course-detail-bottom-right\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"course-info\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"course-info-left\"");

WriteLiteral(@">
                                        <h5>
                                            Số lượng bài giảng
                                        </h5>
                                        <h5>
                                            Thời lượng video
                                        </h5>
                                    </div>
                                    <div");

WriteLiteral(" class=\"course-info-right\"");

WriteLiteral(">\r\n                                        <h5");

WriteLiteral(" class=\"bold\"");

WriteLiteral(">\r\n                                            31\r\n                              " +
"          </h5>\r\n                                        <h5");

WriteLiteral(" class=\"bold\"");

WriteLiteral(">\r\n                                            <span>3h46p</span>\r\n              " +
"                          </h5>\r\n                                    </div>\r\n   " +
"                             </div>\r\n                                <div");

WriteLiteral(" class=\"course-wishlist\"");

WriteLiteral(">\r\n                                    <a");

WriteLiteral(" class=\"btn btn-raised btn-lg wishlist-button wishlisted-bg\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"round\"");

WriteLiteral(">\r\n                                            <i");

WriteLiteral(" class=\"fa fa-heart\"");

WriteLiteral("></i>\r\n                                        </div>\r\n                          " +
"              <span>Quan tâm</span>\r\n                                    </a>\r\n " +
"                                   <a");

WriteLiteral(" class=\"btn social-button\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" id=\"facebook-share-button\"");

WriteLiteral(" style=\"font-size:48px;\"");

WriteLiteral(">\r\n                                        <i");

WriteLiteral(" class=\"fa fa-facebook-square\"");

WriteLiteral("></i>\r\n                                    </a>\r\n                                " +
"</div>\r\n                            </div>\r\n                        </div>\r\n    " +
"                </div>\r\n                </div>\r\n            </div>\r\n            " +
"<div");

WriteLiteral(" class=\"detail-bottom\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"bottom-left\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row no-margin\"");

WriteLiteral(" id=\"description\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row no-margin\"");

WriteLiteral(">\r\n                            <h3");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n                                Mô tả về khóa học ");

            
            #line 177 "..\..\Views\Course\Index.cshtml"
                                             Write(Model.CourseName);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </h3>\r\n                        </div>\r\n            " +
"            <div");

WriteLiteral(" class=\"row no-margin\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 181 "..\..\Views\Course\Index.cshtml"
                       Write(Html.Raw(Model.Content));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                   " +
" <div");

WriteLiteral(" id=\"curiculums\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"curiculums-title\"");

WriteLiteral(">Giáo trình</div>\r\n");

WriteLiteral("                        ");

            
            #line 186 "..\..\Views\Course\Index.cshtml"
                   Write(Html.Partial("~/Views/Course/PartialView/_CourseChildrenTemplate.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" id=\"author\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"author-title\"");

WriteLiteral(">Tiểu sử tác giả</div>\r\n                        <div");

WriteLiteral(" class=\"author-content\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"author-avatar\"");

WriteLiteral(">\r\n                                <img");

WriteLiteral(" style=\"width: 100%\"");

WriteLiteral(" src=\"./Làm chủ Excel 2010 trong 4 giờ_files/nguyen-danh-tu.png\"");

WriteLiteral(" alt=\"Nguyen danh tu\"");

WriteLiteral(">\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"author-description\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"no-margin\"");

WriteLiteral("></div>\r\n                                <a");

WriteLiteral(" class=\"author-title\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(" style=\"color: #464646;\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" style=\"font-size:14px\"");

WriteLiteral(">Thạc sỹ</span>\r\n                                    <span>Tuan Linh</span>\r\n    " +
"                            </a>\r\n                            </div>\r\n          " +
"              </div>\r\n                        <div");

WriteLiteral(" class=\"author-information\"");

WriteLiteral(">\r\n                            <h5");

WriteLiteral(" class=\"information-text\"");

WriteLiteral(">Nguyên Giám đốc tài chính cho Doanh nghiệp có hơn 600 nhân viên</h5>\r\n          " +
"                  <h5");

WriteLiteral(" class=\"information-text\"");

WriteLiteral(">15+ năm kinh nghiệm giảng dạy tại Đại học Bách Khoa Hà Nội và BKIndex</h5>\r\n    " +
"                        <h5");

WriteLiteral(" class=\"information-text\"");

WriteLiteral(">5+ năm kinh nghiệm trong lĩnh vực sư phạm và đào tạo trên môi trường trực tuyến " +
"E-learning.</h5>\r\n                            <h5");

WriteLiteral(" class=\"information-text\"");

WriteLiteral(">12+ năm kinh nghiệm trong lĩnh vực Tin học văn phòng trong công việc và cải tiến" +
" quy trình</h5>\r\n                            <h5");

WriteLiteral(" class=\"information-text\"");

WriteLiteral(">20+ khóa học dành riêng cho người đi làm với chuyên đề Excel.</h5>\r\n            " +
"                <h5");

WriteLiteral(" class=\"information-text\"");

WriteLiteral(">100+ khóa giảng dạy chuyên đề, kỹ năng về ứng dụng CNTT trong làm việc</h5>\r\n   " +
"                     </div>\r\n                    </div>\r\n                    ");

WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"bottom-right\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"also-viewed-container\"");

WriteLiteral(">\r\n                        <h3");

WriteLiteral(" class=\"view-title\"");

WriteLiteral(">Khóa học gợi ý cho bạn</h3>\r\n");

WriteLiteral("                        ");

            
            #line 235 "..\..\Views\Course\Index.cshtml"
                   Write(Html.Partial("~/Views/Course/PartialView/_OtherCoursesTemplate.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n\r\n                </div>\r\n            </div>\r\n     " +
"   </div>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
