#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GiaoDucSomVideo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\Home\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutHome.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 7 "..\..\Views\Home\Index.cshtml"
Write(Html.Partial("~/Views/Home/PartialView/_BannerPartial.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<maim");

WriteLiteral(" class=\"home-page\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"featured-courses row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"wrapper clearfix\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-3 wow fadeInLeft\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"search-box\"");

WriteLiteral(">\r\n                            <form");

WriteLiteral(" action=\"https://edumall.vn/courses/search\"");

WriteLiteral(" mehod=\"get\"");

WriteLiteral(">\r\n                                <input");

WriteLiteral(" name=\"q\"");

WriteLiteral(" placeholder=\"Tìm khóa học\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(">\r\n                                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-search\"");

WriteLiteral("></i>\r\n                                </button>\r\n                            </f" +
"orm>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"list-categories\"");

WriteLiteral(">\r\n                            <ul");

WriteLiteral(" id=\"list-categories\"");

WriteLiteral("></ul>\r\n                        </div>\r\n                    </div>\r\n             " +
"       <div");

WriteLiteral(" class=\"col-md-9 no-padding-left\"");

WriteLiteral(" style=\"position:relative;\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" id=\"wrap_courses_append\"");

WriteLiteral(">\r\n                            \r\n                        </div>\r\n                " +
"    </div>\r\n                </div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"featured-courses-sm\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"list\"");

WriteLiteral(" id=\"detect_swipe\"");

WriteLiteral(" role=\"toolbar\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n                </div>\r\n                <span");

WriteLiteral(" class=\"bottom_line\"");

WriteLiteral("></span>\r\n                <div");

WriteLiteral(" class=\"courses clearfix slick-initialized slick-slider\"");

WriteLiteral(" id=\"courses_swipe\"");

WriteLiteral(" role=\"toolbar\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-role=\"none\"");

WriteLiteral(" class=\"slick-prev slick-arrow slick-disabled\"");

WriteLiteral(" aria-label=\"Previous\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-disabled=\"true\"");

WriteLiteral(" style=\"display: inline-block;\"");

WriteLiteral(">Previous</button>\r\n                    <div");

WriteLiteral(" aria-live=\"polite\"");

WriteLiteral(" class=\"slick-list draggable\"");

WriteLiteral(" style=\"height: 100px;\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" id=\"wrap_courses_sm_append\"");

WriteLiteral(" class=\"slick-track\"");

WriteLiteral(" role=\"listbox\"");

WriteLiteral(" style=\"opacity: 1; width: 0px; left: 0px;\"");

WriteLiteral(">\r\n\r\n                        </div>\r\n                    </div>\r\n                " +
"    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-role=\"none\"");

WriteLiteral(" class=\"slick-next slick-arrow\"");

WriteLiteral(" aria-label=\"Next\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" style=\"display: inline-block;\"");

WriteLiteral(" aria-disabled=\"false\"");

WriteLiteral(">Next</button><ul");

WriteLiteral(" class=\"slick-dots\"");

WriteLiteral(" style=\"display: block;\"");

WriteLiteral(" role=\"tablist\"");

WriteLiteral("><li");

WriteLiteral(" class=\"slick-active\"");

WriteLiteral(" aria-hidden=\"false\"");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" aria-selected=\"true\"");

WriteLiteral(" aria-controls=\"navigation10\"");

WriteLiteral(" id=\"slick-slide10\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-role=\"none\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-required=\"false\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(">1</button></li><li");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" aria-selected=\"false\"");

WriteLiteral(" aria-controls=\"navigation11\"");

WriteLiteral(" id=\"slick-slide11\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-role=\"none\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-required=\"false\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(">2</button></li><li");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" aria-selected=\"false\"");

WriteLiteral(" aria-controls=\"navigation12\"");

WriteLiteral(" id=\"slick-slide12\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-role=\"none\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-required=\"false\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(">3</button></li><li");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" aria-selected=\"false\"");

WriteLiteral(" aria-controls=\"navigation13\"");

WriteLiteral(" id=\"slick-slide13\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-role=\"none\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-required=\"false\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(">4</button></li><li");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" aria-selected=\"false\"");

WriteLiteral(" aria-controls=\"navigation14\"");

WriteLiteral(" id=\"slick-slide14\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-role=\"none\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-required=\"false\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(">5</button></li><li");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" aria-selected=\"false\"");

WriteLiteral(" aria-controls=\"navigation15\"");

WriteLiteral(" id=\"slick-slide15\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-role=\"none\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-required=\"false\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(">6</button></li><li");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" aria-selected=\"false\"");

WriteLiteral(" aria-controls=\"navigation16\"");

WriteLiteral(" id=\"slick-slide16\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-role=\"none\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-required=\"false\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(">7</button></li><li");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" aria-selected=\"false\"");

WriteLiteral(" aria-controls=\"navigation17\"");

WriteLiteral(" id=\"slick-slide17\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-role=\"none\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-required=\"false\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(">8</button></li><li");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" aria-selected=\"false\"");

WriteLiteral(" aria-controls=\"navigation18\"");

WriteLiteral(" id=\"slick-slide18\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-role=\"none\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-required=\"false\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(">9</button></li><li");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" role=\"presentation\"");

WriteLiteral(" aria-selected=\"false\"");

WriteLiteral(" aria-controls=\"navigation19\"");

WriteLiteral(" id=\"slick-slide19\"");

WriteLiteral("><button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" data-role=\"none\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-required=\"false\"");

WriteLiteral(" tabindex=\"0\"");

WriteLiteral(">10</button></li></ul>\r\n                </div>\r\n            </div>\r\n            <" +
"div");

WriteLiteral(" class=\"explore-sm\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(" href=\"https://edumall.vn/courses\"");

WriteLiteral(">Khám phá ngay</a>\r\n                <p>Còn rất nhiều khóa học bổ ích</p>\r\n       " +
"     </div>\r\n\r\n\r\n            <div");

WriteLiteral(" class=\"line-break\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"img-wrap\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n                </div>\r\n                <span></span>\r\n            </div>\r\n    " +
"        \r\n            ");

WriteLiteral("\r\n        </div>\r\n    </div>\r\n</maim>\r\n");

            
            #line 74 "..\..\Views\Home\Index.cshtml"
Write(Html.Partial("~/Views/Home/PartialView/_CoursesTemplatePartial.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 75 "..\..\Views\Home\Index.cshtml"
Write(Html.Partial("~/Views/Home/PartialView/_ListCategorysTemplatePartial.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 76 "..\..\Views\Home\Index.cshtml"
Write(Html.Partial("~/Views/Home/PartialView/_CoursesTemplateSMPartial.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 77 "..\..\Views\Home\Index.cshtml"
Write(Html.Partial("~/Views/Home/PartialView/_ListCategorysTemplateSMPartial.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 8751), Tuple.Create("\"", 8781)
, Tuple.Create(Tuple.Create("", 8757), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.tmpl.js")
, 8757), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 8805), Tuple.Create("\"", 8836)
, Tuple.Create(Tuple.Create("", 8811), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/gds/gds.home.js")
, 8811), false)
);

WriteLiteral("></script>\r\n");

});

WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
