#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GdsVideoBackend;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CategoryDetail/Index.cshtml")]
    public partial class _Views_CategoryDetail_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_CategoryDetail_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\CategoryDetail\Index.cshtml"
  
    ViewBag.Title = "CategoryDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("style", () => {

WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 122), Tuple.Create("\"", 157)
, Tuple.Create(Tuple.Create("", 129), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Style/dropzone.css")
, 129), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

});

WriteLiteral("\r\n");

DefineSection("left_menu", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Views\CategoryDetail\Index.cshtml"
Write(Html.Partial("~/Views/PartialViews/_LeftMenuPartial.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"ibox float-e-margins\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"ibox-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"dataTables_wrapper form-inline\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" class=\"dataTables_length\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                            <label>\r\n                                <select");

WriteLiteral(" class=\"form-control input-sm\"");

WriteLiteral(">\r\n                                    <option");

WriteLiteral(" value=\"50\"");

WriteLiteral(">50</option>\r\n                                    <option");

WriteLiteral(" value=\"100\"");

WriteLiteral(">100</option>\r\n                                </select> records per page\r\n      " +
"                      </label>\r\n                        </div>\r\n                " +
"        <div");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                            <a");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" id=\"show-detail-box\"");

WriteLiteral(" onclick=\"bindingCategoryDetailFrom(this, \'add\')\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" href=\"#add-new-category-detail\"");

WriteLiteral(">Thêm bài học</a>\r\n                        </div>\r\n                    </div>\r\n  " +
"                  <div");

WriteLiteral(" class=\"dataTables_filter\"");

WriteLiteral(">\r\n                        <label>Search:<input");

WriteLiteral(" type=\"search\"");

WriteLiteral(" class=\"form-control input-sm\"");

WriteLiteral(" placeholder=\"\"");

WriteLiteral("></label>\r\n                    </div>\r\n                    <div");

WriteLiteral(" id=\"category_detail_Div\"");

WriteLiteral(">\r\n\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"paging_simple_numbers\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-lg-4\"");

WriteLiteral("></div>\r\n                            <div");

WriteLiteral(" class=\"col-lg-4 paging-row hide\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" class=\"btn btn-default btn-sm prev\"");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-angle-left\"");

WriteLiteral("></i> Previous</a>\r\n                                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"input-mini\"");

WriteLiteral(">&nbsp;of&nbsp;<a");

WriteLiteral(" class=\"total-row\"");

WriteLiteral(">0</a>\r\n                                <a");

WriteLiteral(" class=\"btn btn-default btn-sm next\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Next <i");

WriteLiteral(" class=\"fa fa-angle-right\"");

WriteLiteral("></i></a>\r\n                            </div>\r\n                            <div");

WriteLiteral(" class=\"col-lg-4\"");

WriteLiteral("></div>\r\n                        </div>\r\n                    </div>\r\n            " +
"    </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"add-new-category-detail\"");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                        <h3");

WriteLiteral(" class=\"m-t-none m-b\"");

WriteLiteral(">Thêm Chủ đề</h3>\r\n                        <form");

WriteLiteral(" id=\"category-detail-form\"");

WriteLiteral(" class=\"row\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"form-group col-sm-12\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                    <label>Tên chủ đề</label> <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" placeholder=\"Tên chủ đề\"");

WriteLiteral(" class=\"category-detail-name form-control\"");

WriteLiteral(">\r\n                                </div>\r\n                                <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                    <label>Số thử tự</label> <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" placeholder=\"Số thử tự\"");

WriteLiteral(" class=\"category-detail-index form-control\"");

WriteLiteral(">\r\n                                </div>\r\n                            </div>\r\n  " +
"                          <div");

WriteLiteral(" class=\"form-group col-sm-12\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"file-upload-container dropzone needsclick dz-clickable\"");

WriteLiteral(" style=\"display: none\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"dz-message needsclick\"");

WriteLiteral(">\r\n                                        Drop files here or click to upload.<br" +
">\r\n                                        <span");

WriteLiteral(" class=\"note needsclick\"");

WriteLiteral(">(This is just a demo dropzone. Selected files are <strong>not</strong> actually " +
"uploaded.)</span>\r\n                                    </div>\r\n                 " +
"               </div>\r\n                            </div>\r\n                     " +
"       <div");

WriteLiteral(" class=\"form-group col-sm-12\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" id=\"save\"");

WriteLiteral(" class=\"btn btn-sm btn-primary pull-right m-t-n-xs\"");

WriteLiteral("><strong>Save</strong></a>\r\n                            </div>\r\n                 " +
"           <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"category-detail-id\"");

WriteLiteral(" value=\"0\"");

WriteLiteral(" />\r\n                        </form>\r\n                    </div>\r\n               " +
" </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

            
            #line 93 "..\..\Views\CategoryDetail\Index.cshtml"
Write(Html.Partial("~/Views/CategoryDetail/PatialView/_PhysicalFileTemplate.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 94 "..\..\Views\CategoryDetail\Index.cshtml"
Write(Html.Partial("~/Views/CategoryDetail/PatialView/_CategoryDetailsTemplate.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4737), Tuple.Create("\"", 4767)
, Tuple.Create(Tuple.Create("", 4743), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.tmpl.js")
, 4743), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4791), Tuple.Create("\"", 4828)
, Tuple.Create(Tuple.Create("", 4797), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/gds.paging.control.js")
, 4797), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 4852), Tuple.Create("\"", 4889)
, Tuple.Create(Tuple.Create("", 4858), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/gds.categoryDetail.js")
, 4858), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 4936), Tuple.Create("\"", 4963)
, Tuple.Create(Tuple.Create("", 4942), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/dropzone.js")
, 4942), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        var setupDropzone = function setupDropzone() {
            if ($('.file-upload-container').length === 0) {
                return;
            }
            Dropzone.autoDiscover = false;
            var myDropzone = new Dropzone("".file-upload-container"", {
                previewTemplate: document.querySelector('#preview-template').innerHTML,
                url: '");

            
            #line 109 "..\..\Views\CategoryDetail\Index.cshtml"
                 Write(Url.Action("InsertUpateDetail", "CategoryDetail"));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                method: \"POST\",\r\n                autoProcessQueue: false,\r\n  " +
"              clickable: [\'.file-upload-container\'],\r\n                parallelUp" +
"loads: 1,\r\n                maxFilesize: 100, // in mb\r\n                thumbnail" +
"Width: 150,\r\n                thumbnailHeight: 150,\r\n                thumbnail: f" +
"unction(file, dataUrl) {\r\n                    if (file.previewElement) {\r\n      " +
"                  $(\'#video-content\').val(file);\r\n                        file.p" +
"reviewElement.classList.remove(\"dz-file-preview\");\r\n                        var " +
"images = file.previewElement.querySelectorAll(\"[data-dz-thumbnail]\");\r\n         " +
"               for (var i = 0; i < images.length; i++) {\r\n                      " +
"      var thumbnailElement = images[i];\r\n                            thumbnailEl" +
"ement.alt = file.name;\r\n                            thumbnailElement.src = dataU" +
"rl;\r\n                        }\r\n                        setTimeout(function() { " +
"file.previewElement.classList.add(\"dz-image-preview\"); }, 1);\r\n                 " +
"   }\r\n                },\r\n                queuecomplete: function () {\r\n        " +
"            $(\'#save\').show();\r\n                    $(\'#add-new-category-detail\'" +
").modal(\'hide\');\r\n                    bindingCategoryDetails();\r\n               " +
" },\r\n                sending: function(file, xhr, formData) {\r\n                 " +
"   formData.append(\'CategoryTypeId\', parseInt(gds.getQueryVariable(\'categoryType" +
"Id\')));\r\n                    var categoryDetailId = isNaN($(\"#category-detail-fo" +
"rm #category-detail-id\").val())\r\n                        ? 0\r\n                  " +
"      : parseInt($(\"#category-detail-form #category-detail-id\").val());\r\n       " +
"             formData.append(\'CategoryDetailId\', categoryDetailId);\r\n           " +
"         formData.append(\'LectureIndex\', $(\"#category-detail-form .category-deta" +
"il-index\").val());\r\n                    formData.append(\'CategoryDetailName\', $(" +
"\"#category-detail-form .category-detail-name\").val());\r\n\r\n                }\r\n   " +
"         });\r\n\r\n            $(document).on(\'click\', \'#save\', function (event) {\r" +
"\n                $(\'#save\').hide();\r\n                myDropzone.processQueue();\r" +
"\n            });\r\n        };\r\n        setupDropzone();\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
