#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GdsVideoBackend;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CategoryType/Index.cshtml")]
    public partial class _Views_CategoryType_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_CategoryType_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Views\CategoryType\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("style", () => {

WriteLiteral("\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 110), Tuple.Create("\"", 164)
, Tuple.Create(Tuple.Create("", 117), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/plugins/summernote/summernote.css")
, 117), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 192), Tuple.Create("\"", 250)
, Tuple.Create(Tuple.Create("", 199), Tuple.Create<System.Object, System.Int32>(Href("~/Content/css/plugins/summernote/summernote-bs3.css")
, 199), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

});

WriteLiteral("\r\n");

DefineSection("left_menu", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 14 "..\..\Views\CategoryType\Index.cshtml"
Write(Html.Partial("~/Views/PartialViews/_LeftMenuPartial.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"tabs-container\"");

WriteLiteral(">\r\n        <ul");

WriteLiteral(" class=\"nav nav-tabs\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" id=\"parent-tab\"");

WriteLiteral(" class=\"active\"");

WriteLiteral("><a");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Khóa học</a></li>\r\n            <li");

WriteLiteral(" id=\"children-tab\"");

WriteLiteral(" class=\"\"");

WriteLiteral("><a");

WriteLiteral(" data-toggle=\"tab\"");

WriteLiteral(">Chi tiết khóa học</a></li>\r\n        </ul>\r\n        <div");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"category-type-parent\"");

WriteLiteral(" class=\"tab-pane active\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"ibox float-e-margins\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"ibox-content\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral("  class=\"dataTables_wrapper form-inline\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n                                        <div");

WriteLiteral(" class=\"dataTables_length\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                                                <label>\r\n                     " +
"                               <select");

WriteLiteral(" class=\"form-control input-sm page-size\"");

WriteLiteral(">\r\n                                                        <option");

WriteLiteral(" value=\"50\"");

WriteLiteral(">50</option>\r\n                                                        <option");

WriteLiteral(" value=\"100\"");

WriteLiteral(">100</option>\r\n                                                    </select> reco" +
"rds per page\r\n                                                </label>\r\n        " +
"                                    </div>\r\n                                    " +
"        <div");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" href=\"#add-new-category-type-parent\"");

WriteLiteral(">Thêm khóa học</a>\r\n                                            </div>\r\n         " +
"                               </div>\r\n                                        <" +
"div");

WriteLiteral(" class=\"dataTables_filter\"");

WriteLiteral(">\r\n                                            <label>Search:<input");

WriteLiteral(" type=\"search\"");

WriteLiteral(" class=\"form-control input-sm\"");

WriteLiteral(" placeholder=\"\"");

WriteLiteral("></label>\r\n                                        </div>\r\n                      " +
"                  <div");

WriteLiteral(" id=\"categoryTypeParent_Div\"");

WriteLiteral(">\r\n\r\n                                        </div>\r\n                            " +
"            <div");

WriteLiteral(" class=\"paging_simple_numbers\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"col-lg-4\"");

WriteLiteral("></div>\r\n                                                <div");

WriteLiteral(" class=\"col-lg-4 paging-row hide\"");

WriteLiteral(">\r\n                                                    <a");

WriteLiteral(" class=\"btn btn-default btn-sm prev\"");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-angle-left\"");

WriteLiteral("></i> Previous</a>\r\n                                                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"input-mini\"");

WriteLiteral(">&nbsp;of&nbsp;<a");

WriteLiteral(" class=\"total-row\"");

WriteLiteral(">0</a>\r\n                                                    <a");

WriteLiteral(" class=\"btn btn-default btn-sm next\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Next <i");

WriteLiteral(" class=\"fa fa-angle-right\"");

WriteLiteral("></i></a>\r\n                                                </div>\r\n              " +
"                                  <div");

WriteLiteral(" class=\"col-lg-4\"");

WriteLiteral(@"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div");

WriteLiteral(" id=\"category-type-children\"");

WriteLiteral(" class=\"tab-pane\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"ibox float-e-margins\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"ibox-content\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"table-responsive\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"dataTables_wrapper form-inline\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"clear\"");

WriteLiteral("></div>\r\n                                        <div");

WriteLiteral(" class=\"dataTables_length\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                                                <label>\r\n                     " +
"                               <select");

WriteLiteral(" class=\"form-control input-sm page-size\"");

WriteLiteral(">\r\n                                                        <option");

WriteLiteral(" value=\"50\"");

WriteLiteral(">50</option>\r\n                                                        <option");

WriteLiteral(" value=\"100\"");

WriteLiteral(">100</option>\r\n                                                    </select> reco" +
"rds per page\r\n                                                </label>\r\n        " +
"                                    </div>\r\n                                    " +
"        <div");

WriteLiteral(" class=\"col-sm-3\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" class=\"btn btn-success btn-sm\"");

WriteLiteral(" href=\"#add-new-category-type-children\"");

WriteLiteral(">Thêm khóa học con</a>\r\n                                            </div>\r\n     " +
"                                   </div>\r\n                                     " +
"   \r\n                                        <div");

WriteLiteral(" class=\"dataTables_filter\"");

WriteLiteral(">\r\n                                            <label>Search:<input");

WriteLiteral(" type=\"search\"");

WriteLiteral(" class=\"form-control input-sm\"");

WriteLiteral(" placeholder=\"\"");

WriteLiteral(" ></label>\r\n                                        </div>\r\n                     " +
"                   <div");

WriteLiteral(" id=\"categoryTypeChildren_Div\"");

WriteLiteral(">\r\n\r\n                                        </div>\r\n                            " +
"            <div");

WriteLiteral(" class=\"paging_simple_numbers\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n                                                <div");

WriteLiteral(" class=\"col-lg-4\"");

WriteLiteral("></div>\r\n                                                <div");

WriteLiteral(" class=\"col-lg-4 paging-row hide\"");

WriteLiteral(">\r\n                                                    <a");

WriteLiteral(" class=\"btn btn-default btn-sm prev\"");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-angle-left\"");

WriteLiteral("></i> Previous</a>\r\n                                                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"input-mini\"");

WriteLiteral(">&nbsp;of&nbsp;<a");

WriteLiteral(" class=\"total-row\"");

WriteLiteral(">0</a>\r\n                                                    <a");

WriteLiteral(" class=\"btn btn-default btn-sm next\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">Next <i");

WriteLiteral(" class=\"fa fa-angle-right\"");

WriteLiteral("></i></a>\r\n                                                </div>\r\n              " +
"                                  <div");

WriteLiteral(" class=\"col-lg-4\"");

WriteLiteral(@"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

");

            
            #line 119 "..\..\Views\CategoryType\Index.cshtml"
Write(Html.Partial("~/Views/CategoryType/PatialView/_CategoryTypeChildrenDialog.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 120 "..\..\Views\CategoryType\Index.cshtml"
Write(Html.Partial("~/Views/CategoryType/PatialView/_CategoryTypeChildrenTemplate.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 121 "..\..\Views\CategoryType\Index.cshtml"
Write(Html.Partial("~/Views/CategoryType/PatialView/_CategoryTypeParentDialog.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 122 "..\..\Views\CategoryType\Index.cshtml"
Write(Html.Partial("~/Views/CategoryType/PatialView/_CategoryTypeParentTemplate.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 7243), Tuple.Create("\"", 7273)
, Tuple.Create(Tuple.Create("", 7249), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.tmpl.js")
, 7249), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 7297), Tuple.Create("\"", 7334)
, Tuple.Create(Tuple.Create("", 7303), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/gds.paging.control.js")
, 7303), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 7358), Tuple.Create("\"", 7393)
, Tuple.Create(Tuple.Create("", 7364), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/gds.categorytype.js")
, 7364), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 7417), Tuple.Create("\"", 7472)
, Tuple.Create(Tuple.Create("", 7423), Tuple.Create<System.Object, System.Int32>(Href("~/Content/js/plugins/summernote/summernote.min.js")
, 7423), false)
);

WriteLiteral(@"></script>
    <script>
        $(document).on('click', '#category-type-parent-form #edit', function (event) {
            $('#category-type-parent-form .cateogry-type-content').summernote({ focus: true });
        });
        
        $(document).on('click', '#category-type-parent-form #save', function (event) {
            //var aHTML = $('.cateogry-type-content').code(); //save HTML If you need(aHTML: array).
            $('#category-type-parent-form .cateogry-type-content').destroy();
        });
        
        $(document).on('click', '#category-type-children-form #edit', function (event) {
            $('#category-type-children-form .cateogry-type-content').summernote({ focus: true });
        });

        $(document).on('click', '#category-type-children-form #save', function (event) {
            //var aHTML = $('.cateogry-type-content').code(); //save HTML If you need(aHTML: array).
            $('#category-type-children-form .cateogry-type-content').destroy();
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
