#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GiaoDucSomVideo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/PartialView/_BannerPartial.cshtml")]
    public partial class _Views_Home_PartialView__BannerPartial_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_PartialView__BannerPartial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"home-slider carousel slide\"");

WriteLiteral(" data-interval=\"9000\"");

WriteLiteral(" data-ride=\"carousel\"");

WriteLiteral(" id=\"home_slider\"");

WriteLiteral(">\r\n    <ol");

WriteLiteral(" class=\"carousel-indicators\"");

WriteLiteral(">\r\n        <!-- %li.active{:\'data-slide-to\' => 0, :\'data-target\' => \'#home_slider" +
"\'} -->\r\n        <li");

WriteLiteral(" class=\"\"");

WriteLiteral(" data-slide-to=\"0\"");

WriteLiteral(" data-target=\"#home_slider\"");

WriteLiteral("></li>\r\n        <li");

WriteLiteral(" data-slide-to=\"1\"");

WriteLiteral(" data-target=\"#home_slider\"");

WriteLiteral(" class=\"active\"");

WriteLiteral("></li>\r\n        <li");

WriteLiteral(" data-slide-to=\"2\"");

WriteLiteral(" data-target=\"#home_slider\"");

WriteLiteral(" class=\"\"");

WriteLiteral("></li>\r\n    </ol>\r\n    <div");

WriteLiteral(" class=\"carousel-inner\"");

WriteLiteral(" style=\"height:100%;\"");

WriteLiteral(@">
        <!-- .item.item1.active{:style => 'height:100%;'} -->
        <!-- %a{:href => '/courses', :style => 'width:100%;height:100%;display:block;'} -->
        <!-- .img-big{:style => ""background-image: url(#{image_path('stencil/slider/slide4_1200.jpg')});""} -->
        <!-- = image_tag 'stencil/slider/slide4_1200.jpg', :class => 'img-responsive img-big' -->
        <!-- .img-small{:style => ""background-image: url(#{image_path('stencil/slider/slide4_480.jpg')});""} -->
        <!-- = image_tag 'stencil/slider/slide4_480.jpg', :class => 'img-responsive img-small' -->
        <div");

WriteLiteral(" class=\"item item1\"");

WriteLiteral(" style=\"height:100%;\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"https://edumall.vn/courses\"");

WriteLiteral(" style=\"width:100%;height:100%;display:block;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"img-big\"");

WriteLiteral(" style=\"background-image: url(//static.edumall.vn/assets/stencil/slider/slide1_12" +
"00-fb127d2401f4bd73cfa8d143c2d8e81df76cec1dbcb654a1ad13cd55d6467b1a.jpg);\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" class=\"img-responsive img-big\"");

WriteLiteral(" src=\"./Edumall_files/slide1_1200-fb127d2401f4bd73cfa8d143c2d8e81df76cec1dbcb654a" +
"1ad13cd55d6467b1a.jpg\"");

WriteLiteral(" alt=\"Slide1 1200 fb127d2401f4bd73cfa8d143c2d8e81df76cec1dbcb654a1ad13cd55d6467b1" +
"a\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"img-small\"");

WriteLiteral(" style=\"background-image: url(//static.edumall.vn/assets/stencil/slider/slide1_48" +
"0-479100b07a799df3e0c9eeb751e4f06fdd5048fa2f7e12531eee4f4894bbbca9.jpg);\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" class=\"img-responsive img-small\"");

WriteLiteral(" src=\"./Edumall_files/slide1_480-479100b07a799df3e0c9eeb751e4f06fdd5048fa2f7e1253" +
"1eee4f4894bbbca9.jpg\"");

WriteLiteral(" alt=\"Slide1 480 479100b07a799df3e0c9eeb751e4f06fdd5048fa2f7e12531eee4f4894bbbca9" +
"\"");

WriteLiteral(@">
                </div>
            </a>
            <!-- .carousel-caption -->
            <!-- %h5.title.wow.bounceInDown{:'data-wow-delay' => '0.3s'} Học gì cũng có -->
            <!-- %p.desc.wow.fadeInUp{:'data-wow-delay' => '0.7s'} Từ những chuyên gia nổi tiếng hàng đầu Việt Nam trong mọi lĩnh vực -->
            <!-- %a.link.wow.fadeInUp{:href => '/courses', :'data-wow-delay' => '1s'} Khám phá ngay -->
        </div>
        <div");

WriteLiteral(" class=\"item item2 active\"");

WriteLiteral(" style=\"height:100%;\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"https://edumall.vn/courses\"");

WriteLiteral(" style=\"width:100%;height:100%;display:block;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"img-big\"");

WriteLiteral(" style=\"background-image: url(//static.edumall.vn/assets/stencil/slider/slide2_12" +
"00-9fdce393e561a841abb795825b1dee42b45846b77421edce65e03f8631cede65.jpg);\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" class=\"img-responsive img-big\"");

WriteLiteral(" src=\"./Edumall_files/slide2_1200-9fdce393e561a841abb795825b1dee42b45846b77421edc" +
"e65e03f8631cede65.jpg\"");

WriteLiteral(" alt=\"Slide2 1200 9fdce393e561a841abb795825b1dee42b45846b77421edce65e03f8631cede6" +
"5\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"img-small\"");

WriteLiteral(" style=\"background-image: url(//static.edumall.vn/assets/stencil/slider/slide2_48" +
"0-5128ab344acea526962e0de5c05e77374159da43bb0cd7f137b05c2224604b06.jpg);\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" class=\"img-responsive img-small\"");

WriteLiteral(" src=\"./Edumall_files/slide2_480-5128ab344acea526962e0de5c05e77374159da43bb0cd7f1" +
"37b05c2224604b06.jpg\"");

WriteLiteral(" alt=\"Slide2 480 5128ab344acea526962e0de5c05e77374159da43bb0cd7f137b05c2224604b06" +
"\"");

WriteLiteral(@">
                </div>
            </a>
            <!-- .carousel-caption.hidden-xs -->
            <!-- %h5.title.wow.flipInY{:'data-wow-delay' => '0.5s'} Học qua Video -->
            <!-- %a.link.wow.bounceInUp{:href => '/courses', :'data-wow-delay' => '0.8s'} Khám phá ngay -->
        </div>
        <div");

WriteLiteral(" class=\"item item3\"");

WriteLiteral(" style=\"height:100%;\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" href=\"https://edumall.vn/courses\"");

WriteLiteral(" style=\"width:100%;height:100%;display:block;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"img-big\"");

WriteLiteral(" style=\"background-image: url(//static.edumall.vn/assets/stencil/slider/slide3_12" +
"00-b77f495f567e8d5fc63dfcae59febbbc74d0ade260a0389a36cd470ba9bfefe3.jpg);\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" class=\"img-responsive img-big\"");

WriteLiteral(" src=\"./Edumall_files/slide3_1200-b77f495f567e8d5fc63dfcae59febbbc74d0ade260a0389" +
"a36cd470ba9bfefe3.jpg\"");

WriteLiteral(" alt=\"Slide3 1200 b77f495f567e8d5fc63dfcae59febbbc74d0ade260a0389a36cd470ba9bfefe" +
"3\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"img-small\"");

WriteLiteral(" style=\"background-image: url(//static.edumall.vn/assets/stencil/slider/slide3_48" +
"0-770abac0ab8d54b7d18192f1eed99dae8daa9b2ac2bd45d303b8b1f585faa3a0.jpg);\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" class=\"img-responsive img-small\"");

WriteLiteral(" src=\"./Edumall_files/slide3_480-770abac0ab8d54b7d18192f1eed99dae8daa9b2ac2bd45d3" +
"03b8b1f585faa3a0.jpg\"");

WriteLiteral(" alt=\"Slide3 480 770abac0ab8d54b7d18192f1eed99dae8daa9b2ac2bd45d303b8b1f585faa3a0" +
"\"");

WriteLiteral(@">
                </div>
            </a>
            <!-- .carousel-caption -->
            <!-- .wow.fadeInDown{:'data-wow-delay' => '0.3s'} -->
            <!-- %p.sub-title Uy tín hàng đầu -->
            <!-- %h5.title Đông Nam Á -->
            <!-- %a.wow.bounceIn.link{:href => '/courses', :'data-wow-delay' => '0.8s'} Khám phá ngay -->
        </div>
    </div>
</div>
");

        }
    }
}
#pragma warning restore 1591
