#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GiaoDucSomVideo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/PartialView/_CoursesTemplateSMPartial.cshtml")]
    public partial class _Views_Home_PartialView__CoursesTemplateSMPartial_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_PartialView__CoursesTemplateSMPartial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<script");

WriteLiteral(" id=\"coursesTemplateSM\"");

WriteLiteral(" type=\"text/x-jquery-tmpl\"");

WriteLiteral(@">
    <div class=""course-item-sm slick-slide slick-current slick-active"" id=""wrap_sm_hot_courses"" data-slick-index=""0"" aria-hidden=""false"" tabindex=""-1"" role=""option"" aria-describedby=""slick-slide10"" style=""width: 0px;"">
        {{each CategoryTypes}}
        <div class=""col-md-12"">
            <a href=""${$value.CategoryTypeUrl}"" title=""${$value.CategoryTypeName}"" tabindex=""0"">
                <div class=""item clearfix"">
                    <img class=""img-responsive pull-left"" src=""${$value.ThumbnailImage}"">
                    <div class=""info"">
                        <h3 style=""font-size: 16px;font-weight: 400"">${$value.CategoryTypeName}</h3>
                        <p style=""font-size: 14px;font-weight: 300"">Demo</p>
                    </div>
                </div>
            </a>
        </div>
        {{/each}}
    </div>
</script>");

        }
    }
}
#pragma warning restore 1591
