#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GiaoDucSomVideo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/PartialView/_FeaturedPartial.cshtml")]
    public partial class _Views_Home_PartialView__FeaturedPartial_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_PartialView__FeaturedPartial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"featured-list\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n        <h2");

WriteLiteral(" class=\"wow fadeInDown col-xs-12\"");

WriteLiteral(">Những điểm ưu việt của Edumall</h2>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"item col-md-4 wow fadeInLeft\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"img_wrap\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"./Edumall_files/sa1-0b5f704b13ce831e7e90ffeae51b4e03ee60af1295d7686e21b9e4b" +
"36895714e.png\"");

WriteLiteral(" alt=\"Sa1 0b5f704b13ce831e7e90ffeae51b4e03ee60af1295d7686e21b9e4b36895714e\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"info\"");

WriteLiteral(@">
                <h3>Phương pháp sư phạm LIPE, áp dụng thành công tại Harvard, Stanford...</h3>
                <p>Lộ trình học tập của bạn bao gồm: ""Lecture""-học trên video; ""Interaction""-tương tác với thầy và học viên khác; ""Practice""-thực hành; ""Evaluation""-đánh giá kết quả. Mỗi khóa học có độ dài từ 2-8 giờ video, chia thành nhiều bài học dài từ 3-6 phút hướng đến mục tiêu cụ thể.</p>
            </div>
        </div>
        <div");

WriteLiteral(" class=\"item col-md-4 wow fadeInUp\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"img_wrap\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"./Edumall_files/sa2-4b86ff74d0a111f13bebdb34c74e1628976b5913e95cb7989f80ad5" +
"addc24fef.png\"");

WriteLiteral(" alt=\"Sa2 4b86ff74d0a111f13bebdb34c74e1628976b5913e95cb7989f80ad5addc24fef\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"info\"");

WriteLiteral(@">
                <h3>Học tại nhà, cơ quan, quán cafe, trên máy tính, điện thoại, iPad...</h3>
                <p>Chủ động học tập ở bất kì đâu, vào bất kì lúc nào với thiết bị kết nối internet để đăng nhập vào lớp học trực tuyến. Hệ thống hoạt động 24/7, vì thế hãy tranh thủ thời gian rảnh rỗi để tích lũy thêm kiến thức bổ ích.</p>
            </div>
        </div>
        <div");

WriteLiteral(" class=\"item col-md-4 wow fadeInRight\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"img_wrap\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"./Edumall_files/sa3-8bd6241fcff758bdfbbad0e92428935025537db300f0c713437c471" +
"062693eb0.png\"");

WriteLiteral(" alt=\"Sa3 8bd6241fcff758bdfbbad0e92428935025537db300f0c713437c471062693eb0\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"info\"");

WriteLiteral(@">
                <h3>Sở hữu trọn đời với mức giá chỉ bằng một bữa ăn ngon</h3>
                <p>Bạn được sở hữu tài khoản học tập trọn đời với chi phí mỗi khóa chỉ bằng 1/5 so với các khóa học Offline tương ứng. Tài khoản học trọn đời mà không lo hết hạn. Edumall cam kết hoàn 100% học phí nếu bạn không hài lòng về chất lượng khóa học.</p>
            </div>
        </div>
    </div>
    <div");

WriteLiteral(" class=\"explore col-xs-12 wow fadeInUp\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(" href=\"https://edumall.vn/courses\"");

WriteLiteral(">Khám phá ngay</a>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
