#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GiaoDucSomVideo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/PartialView/_ListCategorysTemplateSMPartial.cshtml")]
    public partial class _Views_Home_PartialView__ListCategorysTemplateSMPartial_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_PartialView__ListCategorysTemplateSMPartial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<script");

WriteLiteral(" id=\"menuCoursesTemplate\"");

WriteLiteral(" type=\"text/x-jquery-tmpl\"");

WriteLiteral(@">
    {{each data}}
    <li class=""active slick-slide slick-current slick-active"" data-slick-index=""${$value.CategoryId}"" aria-hidden=""false"" tabindex=""-1"" role=""option"" aria-describedby=""slick-slide00"">
        <a data-slug=""hot_courses"" href=""#"" tabindex=""0"">
            ${$value.CategoryName}
            <span class=""active_line""></span>
        </a>
    </li>
    {{/each}}
</script>");

        }
    }
}
#pragma warning restore 1591
