#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GiaoDucSomVideo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/PartialView/_ListCategorysTemplatePartial.cshtml")]
    public partial class _Views_Home_PartialView__ListCategorysTemplatePartial_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_PartialView__ListCategorysTemplatePartial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<script");

WriteLiteral(" id=\"menuCoursesTemplate\"");

WriteLiteral(" type=\"text/x-jquery-tmpl\"");

WriteLiteral(">\r\n    {{each data}}\r\n    <li class=\"hot\">\r\n        <a data-slug=\"courses_${$valu" +
"e.CategoryId}\" href=\"#\">${$value.CategoryName}</a>\r\n    </li>\r\n    {{/each}}\r\n</" +
"script>");

        }
    }
}
#pragma warning restore 1591
