#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GiaoDucSomVideo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Category/PartialView/_CouseHotPartialView.cshtml")]
    public partial class _Views_Category_PartialView__CouseHotPartialView_cshtml : System.Web.Mvc.WebViewPage<List<GiaoDucSomVideo.Models.CoursesViewModel>>
    {
        public _Views_Category_PartialView__CouseHotPartialView_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Category\PartialView\_CouseHotPartialView.cshtml"
 foreach (var item in Model)
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"course-card-item\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"course-card\"");

WriteLiteral(">\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 172), Tuple.Create("\"", 194)
            
            #line 6 "..\..\Views\Category\PartialView\_CouseHotPartialView.cshtml"
, Tuple.Create(Tuple.Create("", 179), Tuple.Create<System.Object, System.Int32>(item.UrlCourse
            
            #line default
            #line hidden
, 179), false)
);

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"course-info\"");

WriteLiteral(">\r\n                    <span>8 bài giảng</span>\r\n                    <span>1 giờ " +
"video</span>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"course-image no-margin\"");

WriteLiteral(">\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 435), Tuple.Create("\"", 501)
, Tuple.Create(Tuple.Create("", 441), Tuple.Create("data:image/", 441), true)
            
            #line 12 "..\..\Views\Category\PartialView\_CouseHotPartialView.cshtml"
, Tuple.Create(Tuple.Create("", 452), Tuple.Create<System.Object, System.Int32>(item.MimeTypeImage
            
            #line default
            #line hidden
, 452), false)
, Tuple.Create(Tuple.Create("", 473), Tuple.Create(";base64,", 473), true)
            
            #line 12 "..\..\Views\Category\PartialView\_CouseHotPartialView.cshtml"
, Tuple.Create(Tuple.Create("", 481), Tuple.Create<System.Object, System.Int32>(item.ThumbnailImage
            
            #line default
            #line hidden
, 481), false)
);

WriteLiteral(" alt=\"Course image ttal01 230x130.1\"");

WriteLiteral(">\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"course-card-content\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"row ellipsis-2lines course-title\"");

WriteLiteral(">");

            
            #line 15 "..\..\Views\Category\PartialView\_CouseHotPartialView.cshtml"
                                                             Write(item.CourseName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <div");

WriteLiteral(" class=\"row ellipsis-2lines course-description\"");

WriteLiteral(">Tuan Linh</div>\r\n                    <div");

WriteLiteral(" class=\"row no-margin course-rating\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"rating-container\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(" id=\"percent-rating\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-star rated\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-star rated\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-star rated\"");

WriteLiteral("></i>\r\n                                <span");

WriteLiteral(" class=\"rating-percent\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-star\"");

WriteLiteral("></i>\r\n                                    <i");

WriteLiteral(" class=\"fa fa-star percent\"");

WriteLiteral(" style=\"width: 70.00000000000001%\"");

WriteLiteral("></i>\r\n                                </span>\r\n                                <" +
"i");

WriteLiteral(" class=\"fa fa-star\"");

WriteLiteral("></i>\r\n                            </div>\r\n                        </div>\r\n      " +
"              </div>\r\n                    <div");

WriteLiteral(" class=\"row no-margin course-price\"");

WriteLiteral(">");

            
            #line 31 "..\..\Views\Category\PartialView\_CouseHotPartialView.cshtml"
                                                        Write(item.Price);

            
            #line default
            #line hidden
WriteLiteral("đ</div>\r\n                </div>\r\n            </a>\r\n            <div");

WriteLiteral(" class=\"course-wishlist\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" class=\"wishlist-heart\"");

WriteLiteral(" val=\"5627585fd8b7313836000002\"");

WriteLiteral(">\r\n                    <svg");

WriteLiteral(" height=\"18\"");

WriteLiteral(" preserveAspectRatio=\"xMidYMid\"");

WriteLiteral(" viewBox=\"0 0 20 18\"");

WriteLiteral(" width=\"18\"");

WriteLiteral(" xmlns:xlink=\"http://www.w3.org/1999/xlink\"");

WriteLiteral(" xmlns=\"http://www.w3.org/2000/svg\"");

WriteLiteral(@">
                        <defs>
                            <style>
                                .heart {
                                    fill: #ffffff;
                                    stroke: # none;
                                    stroke-linejoin: round;
                                    stroke-width: 1px;
                                    fill-rule: evenodd;
                                }

                                .heart:hover {
                                    fill: #ffffff;
                                }

                                .wishlist {
                                    fill: #ffffff;
                                }
                            </style>
                        </defs>
                        <path");

WriteLiteral(" class=\"heart\"");

WriteLiteral(@" d=""M10.000,17.000 L8.740,15.783 C4.060,11.783 1.000,9.087 1.000,5.783 C1.000,3.087 3.160,1.000 5.950,1.000 C7.480,1.000 9.010,1.696 10.000,2.826 C10.990,1.696 12.520,1.000 14.050,1.000 C16.840,1.000 19.000,3.087 19.000,5.783 C19.000,9.087 15.940,11.783 11.260,15.783 L10.000,17.000 Z""");

WriteLiteral("></path>\r\n                    </svg>\r\n                    <div");

WriteLiteral(" class=\"wishlist-tooltip\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"wishlist-tooltip-bg\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-sort-asc wishlist-tooltip-arrow\"");

WriteLiteral("></i>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"wishlist-tooltip-inner\"");

WriteLiteral(">\r\n                            <span");

WriteLiteral(" style=\"font-size: 12px;\"");

WriteLiteral(">Quan tâm</span>\r\n                        </div>\r\n                    </div>\r\n   " +
"             </a>\r\n            </div>\r\n        </div>\r\n    \r\n    </div>\r\n");

            
            #line 71 "..\..\Views\Category\PartialView\_CouseHotPartialView.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
