#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GiaoDucSomVideo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Category/PartialView/_CousesResult.cshtml")]
    public partial class _Views_Category_PartialView__CousesResult_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Category_PartialView__CousesResult_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"cousesResultTemplate\"");

WriteLiteral(" type=\"text/x-jquery-tmpl\"");

WriteLiteral(">\r\n    {{each Result}}\r\n    <div class=\"search-card\">\r\n        <a href=\"${$value." +
"UrlCourse}\">\r\n        </a>\r\n        <div class=\"row no-margin rel\">\r\n           " +
" <a href=\"${$value.UrlCourse}\">\r\n                <div class=\"image-course pull-l" +
"eft\" style=\"background-image: url(data:image/${$value.MimeTypeImage};base64,${$v" +
"alue.ThumbnailImage})\"></div>\r\n                <div class=\"content-course\">\r\n   " +
"                 <div class=\"name-course\">${$value.CourseName}</div>\r\n          " +
"          <div class=\"about-author\">\r\n                        <span>Tuan Linh</s" +
"pan>\r\n                        <span></span>\r\n                    </div>\r\n       " +
"             <div class=\"info-course row no-margin\">\r\n                        <d" +
"iv class=\"real-price info-item\">\r\n                            ${$value.Price}đ\r\n" +
"                        </div>\r\n                        <div id=\"rating\">\r\n     " +
"                       <div class=\"search-rating\">\r\n                            " +
"    <div class=\"search-rating-star\">\r\n                                    <div c" +
"lass=\"pull-left\" id=\"percent-rating\">\r\n                                        <" +
"i class=\"fa fa-star rated\"></i>\r\n                                        <i clas" +
"s=\"fa fa-star rated\"></i>\r\n                                        <i class=\"fa " +
"fa-star rated\"></i>\r\n                                        <span class=\"rating" +
"-percent\">\r\n                                            <i class=\"fa fa-star\"></" +
"i>\r\n                                            <i class=\"fa fa-star percent\" st" +
"yle=\"width: 39.99999999999999%\"></i>\r\n                                        </" +
"span>\r\n                                        <i class=\"fa fa-star\"></i>\r\n     " +
"                               </div>\r\n                                </div>\r\n " +
"                           </div>\r\n                        </div>\r\n             " +
"           <div class=\"short-rating\">\r\n                            <i class=\"fa " +
"fa-star rated\">\r\n                                <span class=\"course-people-rati" +
"ng\"> 3.4</span>\r\n                            </i>\r\n                        </div" +
">\r\n                    </div>\r\n                </div>\r\n            </a>\r\n       " +
"     <div class=\"course-wishlist abs\">\r\n                <a href=\"${$value.UrlCou" +
"rse}\">\r\n                </a>\r\n                <a class=\"wishlist-heart\" val=\"562" +
"ef71ed8b731249400004f\">\r\n                    <svg height=\"18\" preserveAspectRati" +
"o=\"xMidYMid\" viewBox=\"0 0 20 18\" width=\"18\" xmlns:xlink=\"http://www.w3.org/1999/" +
"xlink\" xmlns=\"http://www.w3.org/2000/svg\">\r\n                        <defs>\r\n    " +
"                        <style>\r\n                                .heart {\r\n     " +
"                               fill: #ffffff;\r\n                                 " +
"   stroke: #none;\r\n                                    stroke-linejoin: round;\r\n" +
"                                    stroke-width: 1px;\r\n                        " +
"            fill-rule: evenodd;\r\n                                }\r\n\r\n          " +
"                      .heart:hover {\r\n                                    fill: " +
"#ffffff;\r\n                                }\r\n\r\n                                ." +
"wishlist {\r\n                                    fill: #ffffff;\r\n                " +
"                }\r\n                            </style>\r\n                       " +
" </defs>\r\n                        <path class=\"heart\" d=\"M10.000,17.000 L8.740,1" +
"5.783 C4.060,11.783 1.000,9.087 1.000,5.783 C1.000,3.087 3.160,1.000 5.950,1.000" +
" C7.480,1.000 9.010,1.696 10.000,2.826 C10.990,1.696 12.520,1.000 14.050,1.000 C" +
"16.840,1.000 19.000,3.087 19.000,5.783 C19.000,9.087 15.940,11.783 11.260,15.783" +
" L10.000,17.000 Z\"></path>\r\n                    </svg>\r\n                    <div" +
" class=\"wishlist-tooltip\">\r\n                        <div class=\"wishlist-tooltip" +
"-bg\">\r\n                            <i class=\"fa fa-sort-asc wishlist-tooltip-arr" +
"ow\"></i>\r\n                        </div>\r\n                        <div class=\"wi" +
"shlist-tooltip-inner\">\r\n                            <span style=\"font-size: 12px" +
";\">Quan tâm</span>\r\n                        </div>\r\n                    </div>\r\n" +
"                </a>\r\n            </div>\r\n        </div>\r\n    </div>\r\n    {{/eac" +
"h}}\r\n</script>");

        }
    }
}
#pragma warning restore 1591
