#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GiaoDucSomVideo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Course/PartialView/_CourseChildrenTemplate.cshtml")]
    public partial class _Views_Course_PartialView__CourseChildrenTemplate_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Course_PartialView__CourseChildrenTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"curiculum\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row no-margin curiculum-title\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" class=\"normal-text\"");

WriteLiteral(" href=\"https://edumall.vn/courses/lam-chu-excel-2010-trong-4-gio/detail#\"");

WriteLiteral(" style=\"pointer-events: none; margin: 15px 0; color: #464646;\"");

WriteLiteral(">\r\n            <b>Phần 1: Nội dung khóa học</b>\r\n        </a>\r\n    </div>\r\n</div>" +
"\r\n<div");

WriteLiteral(" class=\"curiculum\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row no-margin curiculum-list\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-xs-12 no-padding\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row no-margin curiculum-content\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"detail-curi-type pull-left\"");

WriteLiteral(" style=\"margin-right:10px\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"fa fa-play-circle\"");

WriteLiteral("></i>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"detail-curi-lecture pull-left\"");

WriteLiteral(">\r\n                        <h5");

WriteLiteral(" class=\"normal-text no-margin\"");

WriteLiteral(" style=\"line-height:1.5; color: #777777\"");

WriteLiteral(">Bài số 1</h5>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"detail-curi-title pull-left\"");

WriteLiteral(">\r\n                        <h5");

WriteLiteral(" class=\"normal-text no-margin\"");

WriteLiteral(" style=\"line-height:1.5; color: #777777\"");

WriteLiteral(">Giới thiệu</h5>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"detail-curi-leacture pull-right\"");

WriteLiteral(">\r\n                        <h5");

WriteLiteral(" class=\"normal-text no-margin\"");

WriteLiteral(">\r\n                            <b>03:55</b>\r\n                        </h5>\r\n     " +
"               </div>\r\n                </div>\r\n            </div>\r\n        </div" +
">\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
