#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GiaoDucSomVideo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Course/PartialView/_OtherCoursesTemplate.cshtml")]
    public partial class _Views_Course_PartialView__OtherCoursesTemplate_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Course_PartialView__OtherCoursesTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<ul");

WriteLiteral(" class=\"also-viewed\"");

WriteLiteral(">\r\n    <li");

WriteLiteral(" class=\"also-viewed-item\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-md-6 course-image\"");

WriteLiteral(">\r\n                <a");

WriteLiteral(" href=\"https://edumall.vn/courses/lam-chu-excel-trong-4-gio/detail?feat=rec&amp;p" +
"os=detail\"");

WriteLiteral(" title=\"Học Excel 2007 cơ bản\"");

WriteLiteral(">\r\n                    <img");

WriteLiteral(" alt=\"Học Excel 2007 cơ bản\"");

WriteLiteral(" class=\"img-responsive\"");

WriteLiteral(" src=\"./Làm chủ Excel 2010 trong 4 giờ_files/course_image_abc.jpg\"");

WriteLiteral(">\r\n                </a>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"col-md-6 course-description\"");

WriteLiteral(">\r\n                <div>\r\n                    <a");

WriteLiteral(" href=\"https://edumall.vn/courses/lam-chu-excel-trong-4-gio/detail?feat=rec&amp;p" +
"os=detail\"");

WriteLiteral(" title=\"Học Excel 2007 cơ bản\"");

WriteLiteral(">Học Excel 2007 cơ bản</a>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"price\"");

WriteLiteral(">599.000 đ</div>\r\n                <div");

WriteLiteral(" class=\"row no-margin course-rating\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"rating-container\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"pull-left\"");

WriteLiteral(" id=\"percent-rating\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-star rated\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-star rated\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-star rated\"");

WriteLiteral("></i>\r\n                            <i");

WriteLiteral(" class=\"fa fa-star rated\"");

WriteLiteral("></i>\r\n                            <span");

WriteLiteral(" class=\"rating-percent\"");

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-star\"");

WriteLiteral("></i>\r\n                                <i");

WriteLiteral(" class=\"fa fa-star percent\"");

WriteLiteral(" style=\"width: 79.99999999999999%\"");

WriteLiteral("></i>\r\n                            </span>\r\n                        </div>\r\n     " +
"               </div>\r\n                </div>\r\n            </div>\r\n        </div" +
">\r\n    </li>\r\n</ul>\r\n");

        }
    }
}
#pragma warning restore 1591
