#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GiaoDucSomVideo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_LeftMenuContent.cshtml")]
    public partial class _Views_Shared__LeftMenuContent_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__LeftMenuContent_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"otherCategoryLeftMenu\"");

WriteLiteral(" type=\"text/x-jquery-tmpl\"");

WriteLiteral(@">
    <div class=""row no-margin other-category-container hidden-sm"">
        <label style=""color: #338abc;"">Các lĩnh vực khác</label>
        <div class=""row no-margin other-category"">
            <a class=""other-category-item"" href=""https://edumall.vn/cong-nghe-thong-tin"">Công nghệ thông tin</a>
            <a class=""other-category-item"" href=""https://edumall.vn/nuoi-day-con"">Nuôi dạy con</a>
            <a class=""other-category-item"" href=""https://edumall.vn/ky-nang-mem"">Phát triển cá nhân</a>
            <a class=""other-category-item"" href=""https://edumall.vn/kinh-doanh-lam-giau"">Kinh doanh và khởi nghiệp</a>
            <a class=""other-category-item"" href=""https://edumall.vn/tieng-anh-nghe-thuat"">Tiếng Anh</a>
            <a class=""other-category-item"" href=""https://edumall.vn/thiet-ke"">Thiết kế</a>
            <a class=""other-category-item"" href=""https://edumall.vn/marketing"">Marketing</a>
            <a class=""other-category-item"" href=""https://edumall.vn/ung-dung-van-phong"">Ứng dụng văn phòng</a>
            <a class=""other-category-item"" href=""https://edumall.vn/chu-de-khac"">Chủ đề khác</a>
        </div>
    </div>
</script>

<div");

WriteLiteral(" class=\"row no-margin other-category-container hidden-sm\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" style=\"color: #338abc;\"");

WriteLiteral(">Các lĩnh vực khác</label>\r\n    <div");

WriteLiteral(" class=\"row no-margin other-category\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" class=\"other-category-item\"");

WriteLiteral(" href=\"https://edumall.vn/cong-nghe-thong-tin\"");

WriteLiteral(">Công nghệ thông tin</a>\r\n        <a");

WriteLiteral(" class=\"other-category-item\"");

WriteLiteral(" href=\"https://edumall.vn/nuoi-day-con\"");

WriteLiteral(">Nuôi dạy con</a>\r\n        <a");

WriteLiteral(" class=\"other-category-item\"");

WriteLiteral(" href=\"https://edumall.vn/ky-nang-mem\"");

WriteLiteral(">Phát triển cá nhân</a>\r\n        <a");

WriteLiteral(" class=\"other-category-item\"");

WriteLiteral(" href=\"https://edumall.vn/kinh-doanh-lam-giau\"");

WriteLiteral(">Kinh doanh và khởi nghiệp</a>\r\n        <a");

WriteLiteral(" class=\"other-category-item\"");

WriteLiteral(" href=\"https://edumall.vn/tieng-anh-nghe-thuat\"");

WriteLiteral(">Tiếng Anh</a>\r\n        <a");

WriteLiteral(" class=\"other-category-item\"");

WriteLiteral(" href=\"https://edumall.vn/thiet-ke\"");

WriteLiteral(">Thiết kế</a>\r\n        <a");

WriteLiteral(" class=\"other-category-item\"");

WriteLiteral(" href=\"https://edumall.vn/marketing\"");

WriteLiteral(">Marketing</a>\r\n        <a");

WriteLiteral(" class=\"other-category-item\"");

WriteLiteral(" href=\"https://edumall.vn/ung-dung-van-phong\"");

WriteLiteral(">Ứng dụng văn phòng</a>\r\n        <a");

WriteLiteral(" class=\"other-category-item\"");

WriteLiteral(" href=\"https://edumall.vn/chu-de-khac\"");

WriteLiteral(">Chủ đề khác</a>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
