#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GiaoDucSomVideo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_LeftMenuContent.cshtml")]
    public partial class _Views_Shared__LeftMenuContent_cshtml : System.Web.Mvc.WebViewPage<List<GiaoDucSomVideo.Models.CategoryLeftMenuViewModel>>
    {
        public _Views_Shared__LeftMenuContent_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"row no-margin other-category-container hidden-sm\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" style=\"color: #338abc;\"");

WriteLiteral(">Các lĩnh vực khác</label>\r\n    <div");

WriteLiteral(" class=\"row no-margin other-category\"");

WriteLiteral(">\r\n");

            
            #line 6 "..\..\Views\Shared\_LeftMenuContent.cshtml"
        
            
            #line default
            #line hidden
            
            #line 6 "..\..\Views\Shared\_LeftMenuContent.cshtml"
         foreach (var item in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" class=\"other-category-item\"");

WriteAttribute("href", Tuple.Create(" href=\"", 330), Tuple.Create("\"", 354)
            
            #line 8 "..\..\Views\Shared\_LeftMenuContent.cshtml"
, Tuple.Create(Tuple.Create("", 337), Tuple.Create<System.Object, System.Int32>(item.UrlCategory
            
            #line default
            #line hidden
, 337), false)
);

WriteLiteral(">");

            
            #line 8 "..\..\Views\Shared\_LeftMenuContent.cshtml"
                                                               Write(item.CategoryName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 9 "..\..\Views\Shared\_LeftMenuContent.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
