#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GiaoDucSomVideo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_MenuTopPage.cshtml")]
    public partial class _Views_Shared__MenuTopPage_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__MenuTopPage_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<ul");

WriteLiteral(" class=\"dropdown-menu sidebar-category\"");

WriteLiteral(">\r\n    <li");

WriteLiteral(" class=\"btn btn-flat category-item my-course\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"https://edumall.vn/home/my-course/learning\"");

WriteLiteral(">Khóa học của tôi</a>\r\n    </li>\r\n    <li");

WriteLiteral(" class=\"btn btn-flat category-item it\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"https://edumall.vn/cong-nghe-thong-tin\"");

WriteLiteral(">Công nghệ thông tin</a>\r\n    </li>\r\n    <li");

WriteLiteral(" class=\"btn btn-flat category-item children\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"https://edumall.vn/nuoi-day-con\"");

WriteLiteral(">Nuôi dạy con</a>\r\n    </li>\r\n    <li");

WriteLiteral(" class=\"btn btn-flat category-item personal\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"https://edumall.vn/ky-nang-mem\"");

WriteLiteral(">Phát triển cá nhân</a>\r\n    </li>\r\n    <li");

WriteLiteral(" class=\"btn btn-flat business category-item\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"https://edumall.vn/kinh-doanh-lam-giau\"");

WriteLiteral(">Kinh doanh và khởi nghiệp</a>\r\n    </li>\r\n    <li");

WriteLiteral(" class=\"btn btn-flat category-item english\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"https://edumall.vn/tieng-anh-nghe-thuat\"");

WriteLiteral(">Tiếng Anh</a>\r\n    </li>\r\n    <li");

WriteLiteral(" class=\"btn btn-flat category-item design\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"https://edumall.vn/thiet-ke\"");

WriteLiteral(">Thiết kế</a>\r\n    </li>\r\n    <li");

WriteLiteral(" class=\"btn btn-flat category-item marketing\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"https://edumall.vn/marketing\"");

WriteLiteral(">Marketing</a>\r\n    </li>\r\n    <li");

WriteLiteral(" class=\"btn btn-flat category-item office\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"https://edumall.vn/ung-dung-van-phong\"");

WriteLiteral(">Ứng dụng văn phòng</a>\r\n    </li>\r\n    <li");

WriteLiteral(" class=\"btn btn-flat category-item other\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"https://edumall.vn/chu-de-khac\"");

WriteLiteral(">Chủ đề khác</a>\r\n    </li>\r\n</ul>\r\n");

        }
    }
}
#pragma warning restore 1591
