#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GdsVideoBackend;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/CategoryDetail/PatialView/_CategoryDetailsTemplate.cshtml")]
    public partial class _Views_CategoryDetail_PatialView__CategoryDetailsTemplate_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_CategoryDetail_PatialView__CategoryDetailsTemplate_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" id=\"categoryDetailTemplate\"");

WriteLiteral(" type=\"text/x-jquery-tmpl\"");

WriteLiteral(">\r\n    <table class=\"table table-striped table-bordered table-hover dataTable dtr" +
"-inline\" id=\"categoryDetailTemplate_Table\" role=\"grid\" aria-describedby=\"DataTab" +
"les_Table_0_info\">\r\n        <thead>\r\n            <tr role=\"row\">\r\n              " +
"  <th class=\"sorting_asc\" tabindex=\"0\" aria-controls=\"categoryDetailTemplate_Tab" +
"le\" rowspan=\"1\" colspan=\"1\" aria-sort=\"ascending\" style=\"width: 189px;\">Tên bài<" +
"/th>\r\n                <th class=\"sorting_asc\" tabindex=\"0\" aria-controls=\"catego" +
"ryDetailTemplate_Table\" rowspan=\"1\" colspan=\"1\" aria-sort=\"ascending\" style=\"wid" +
"th: 189px;\">Nội dung</th>\r\n                <th class=\"sorting_asc\" tabindex=\"0\" " +
"aria-controls=\"categoryDetailTemplate_Table\" rowspan=\"1\" colspan=\"1\" aria-sort=\"" +
"ascending\" style=\"width: 189px;\">Tên file</th>\r\n                <th class=\"sorti" +
"ng\" tabindex=\"0\" aria-controls=\"categoryDetailTemplate_Table\" rowspan=\"1\" colspa" +
"n=\"1\" style=\"width: 162px;\">Ngày tạo</th>\r\n                <th tabindex=\"0\" aria" +
"-controls=\"categoryDetailTemplate_Table\" rowspan=\"1\" colspan=\"1\" style=\"width: 1" +
"15px;\"></th>\r\n            </tr>\r\n        </thead>\r\n        <tbody>\r\n            " +
"{{each Result}}\r\n            <tr class=\"odd\" role=\"row\" id=\"${$value.CategoryDet" +
"ailId}\">\r\n                <td class=\"categorty-detail\">${$value.CategoryDetailNa" +
"me}</td>\r\n                <td class=\"content\">${$value.Content}</td>\r\n          " +
"      <td class=\"fileName\">${$value.FileName}</td>\r\n                <td class=\"c" +
"reate-date\">${$value.UpdatedDate}</td>\r\n                <td class=\"actions\">\r\n  " +
"                  <a class=\"btn btn-sm btn-success btn-rounded show-detail-box\" " +
"onclick=\"bindingCategoryDetailFrom(this, \'edit\')\" data-id=\"${$value.CategoryDeta" +
"ilId}\" data-toggle=\"modal\" href=\"#add-new-category-detail\">Edit</a>\r\n           " +
"         <a class=\"btn btn-sm btn-danger btn-rounded\" onclick=\"deleteCategoryDet" +
"ail(this)\" data-id=\"${$value.CategoryDetailId}\" href=\"#\">Delete</a>\r\n           " +
"     </td>\r\n            </tr>\r\n            {{/each}}\r\n        </tbody>\r\n    </ta" +
"ble>\r\n</script>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
