#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using GiaoDucSomVideo;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Category/Index.cshtml")]
    public partial class _Views_Category_Index_cshtml : System.Web.Mvc.WebViewPage<GiaoDucSomVideo.Models.CategoryViewModel>
    {
        public _Views_Category_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Category\Index.cshtml"
  
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("<div");

WriteLiteral(" class=\"container-wrapper\"");

WriteLiteral(" style=\"overflow: hidden;\"");

WriteLiteral(">\r\n    <main");

WriteLiteral(" class=\"category\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row no-margin category-header\"");

WriteLiteral(" style=\"background-color: background-color: #3a4f54;background: linear-gradient(-" +
"90deg, #577780, #36494e);\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row container\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"no-padding breadcrumb\"");

WriteLiteral(">\r\n                    <li>\r\n                        <a");

WriteLiteral(" href=\"https://edumall.vn/\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-home\"");

WriteLiteral("></i>\r\n                        </a>\r\n                    </li>\r\n                 " +
"   <li");

WriteLiteral(" class=\"breadcrumb-home\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" href=\"https://edumall.vn/\"");

WriteLiteral(">Trang chủ</a>\r\n                    </li>\r\n                    <li>");

            
            #line 19 "..\..\Views\Category\Index.cshtml"
                   Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                </ul>\r\n                <div");

WriteLiteral(" class=\"row no-margin category-header-name\"");

WriteLiteral(">\r\n                    <h2>");

            
            #line 22 "..\..\Views\Category\Index.cshtml"
                   Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"row no-margin category-all-courses\"");

WriteLiteral(" id=\"parent_style\"");

WriteLiteral(@">
            <style>
                .other-category a {
                    color: #960075 !important;
                }
            </style>
            <style>
                .other-category a:hover {
                    font-weight: bold !important;
                }
            </style>
            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-3 col-md-3 col-sm-12 no-padding category-all-courses-left\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"filter hide clearfix\"");

WriteLiteral(">\r\n                        <form");

WriteLiteral(" action=\"https://edumall.vn/nuoi-day-con\"");

WriteLiteral(" id=\"filter-form\"");

WriteLiteral(" method=\"GET\"");

WriteLiteral(" name=\"filter-form\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row filter-category filter-budget\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"filter-category-title\"");

WriteLiteral(">Chi phí</span>\r\n                                <div");

WriteLiteral(" class=\"row no-margin filter-category-content checkbox-ui\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-xs-6 col-sm-6 col-md-12 col-lg-12 no-padding filter-category-item\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"checkbox-group\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" id=\"check-free\"");

WriteLiteral(" name=\"budget\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"free\"");

WriteLiteral(">\r\n                                            <label");

WriteLiteral(" for=\"check-free\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"check\"");

WriteLiteral("></span>\r\n                                                <span");

WriteLiteral(" class=\"box\"");

WriteLiteral("></span>\r\n                                                Miễn phí\r\n             " +
"                               </label>\r\n                                       " +
" </div>\r\n                                    </div>\r\n                           " +
"         <div");

WriteLiteral(" class=\"col-xs-6 col-sm-6 col-md-12 col-lg-12 no-padding filter-category-item\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"checkbox-group\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" id=\"check-pay\"");

WriteLiteral(" name=\"budget\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"paid\"");

WriteLiteral(">\r\n                                            <label");

WriteLiteral(" for=\"check-pay\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"check\"");

WriteLiteral("></span>\r\n                                                <span");

WriteLiteral(" class=\"box\"");

WriteLiteral(@"></span>
                                                Trả phí
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div");

WriteLiteral(" class=\"row filter-category filter-feature\"");

WriteLiteral(">\r\n                                <span");

WriteLiteral(" class=\"filter-category-title\"");

WriteLiteral(">Tính năng</span>\r\n                                <div");

WriteLiteral(" class=\"row no-margin filter-category-content checkbox-ui\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"col-xs-6 col-sm-6 col-md-12 col-lg-12 no-padding filter-category-item\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"checkbox-group\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" id=\"check-sub\"");

WriteLiteral(" name=\"feature\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"sub\"");

WriteLiteral(">\r\n                                            <label");

WriteLiteral(" for=\"check-sub\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"check\"");

WriteLiteral("></span>\r\n                                                <span");

WriteLiteral(" class=\"box\"");

WriteLiteral("></span>\r\n                                                Phụ đề\r\n               " +
"                             </label>\r\n                                        <" +
"/div>\r\n                                    </div>\r\n                             " +
"       <div");

WriteLiteral(" class=\"col-xs-6 col-sm-6 col-md-12 col-lg-12 no-padding filter-category-item\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"checkbox-group\"");

WriteLiteral(">\r\n                                            <input");

WriteLiteral(" id=\"check-ex\"");

WriteLiteral(" name=\"feature\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" value=\"exam\"");

WriteLiteral(">\r\n                                            <label");

WriteLiteral(" for=\"check-ex\"");

WriteLiteral(">\r\n                                                <span");

WriteLiteral(" class=\"check\"");

WriteLiteral("></span>\r\n                                                <span");

WriteLiteral(" class=\"box\"");

WriteLiteral(@"></span>
                                                Bài tập
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
");

WriteLiteral("                    ");

            
            #line 93 "..\..\Views\Category\Index.cshtml"
               Write(Html.Partial("~/Views/Shared/_LeftMenuContent.cshtml", Model.LeftMenu));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-lg-9 col-md-9 col-sm-12 category-all-courses-main\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"banner\"");

WriteLiteral(">\r\n\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"row no-margin\"");

WriteLiteral(">\r\n                        <h3>Các khóa học nổi bật</h3>\r\n                    </d" +
"iv>\r\n                    <!-- To be showed on desktop -->\r\n                    <" +
"div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"card-category\"");

WriteLiteral(" id=\"courses_slider\"");

WriteLiteral(" style=\"position:relative;overflow:hidden;height:277px;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"pre-card\"");

WriteLiteral(" style=\"position:absolute;top:45px;left:0px;background-color:#ffffff;\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" data-slide=\"prev\"");

WriteLiteral(" href=\"https://edumall.vn/nuoi-day-con#\"");

WriteLiteral(" style=\"display:block;\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-chevron-left\"");

WriteLiteral("></i>\r\n                                </a>\r\n                            </div>\r\n" +
"                            <div");

WriteLiteral(" class=\"next-card\"");

WriteLiteral(" style=\"position:absolute;top:45px;right:0px;background-color:#ffffff;\"");

WriteLiteral(">\r\n                                <a");

WriteLiteral(" data-slide=\"next\"");

WriteLiteral(" href=\"https://edumall.vn/nuoi-day-con#\"");

WriteLiteral(" style=\"display:block;\"");

WriteLiteral(">\r\n                                    <i");

WriteLiteral(" class=\"fa fa-chevron-right\"");

WriteLiteral("></i>\r\n                                </a>\r\n                            </div>\r\n" +
"                            <div");

WriteLiteral(" class=\"category-inner clearfix\"");

WriteLiteral(" style=\"width:20000px;position:absolute;top:0;left:0;\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 116 "..\..\Views\Category\Index.cshtml"
                           Write(Html.Partial("~/Views/Category/PartialView/_CouseHotPartialView.cshtml", Model.CoursesHot));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"         </div>\r\n                    <!-- To be showed on mobile -->\r\n          " +
"          <div");

WriteLiteral(" class=\"row no-margin feature-course-in-list\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 122 "..\..\Views\Category\Index.cshtml"
                   Write(Html.Partial("~/Views/Category/PartialView/_CouseHotSMPartialView.cshtml", Model.CoursesHot));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n\r\n                    <h3>Tất cả các khóa học</h3>\r" +
"\n                    <div");

WriteLiteral(" class=\"row no-margin courses-sorting\"");

WriteLiteral(">\r\n                        <form");

WriteLiteral(" action=\"https://edumall.vn/nuoi-day-con\"");

WriteLiteral(" id=\"sorting-form\"");

WriteLiteral(" method=\"GET\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" id=\"sorting\"");

WriteLiteral(" name=\"ordering\"");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(">\r\n                        </form>\r\n                        <ul");

WriteLiteral(" class=\"pull-right\"");

WriteLiteral(">\r\n                            <li");

WriteLiteral(" class=\"courses-sorting-title\"");

WriteLiteral(">\r\n                                Sắp xếp\r\n                            </li>\r\n  " +
"                          <li>\r\n                                <div");

WriteLiteral(" class=\"dropdown\"");

WriteLiteral(">\r\n                                    <span");

WriteLiteral(" class=\"courses-sorting-selected dropdown-toggle\"");

WriteLiteral(" data-target=\"#\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(">\r\n                                        Mặc định\r\n                            " +
"            <b");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></b>\r\n                                    </span>\r\n                             " +
"       <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n                                        <li>\r\n                                " +
"            <a");

WriteLiteral(" class=\"courses-sorting-select\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(" value=\"price-low-to-high\"");

WriteLiteral(">Giá từ thấp đến cao</a>\r\n                                        </li>\r\n        " +
"                                <li>\r\n                                          " +
"  <a");

WriteLiteral(" class=\"courses-sorting-select\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(" value=\"price-high-to-low\"");

WriteLiteral(@">Giá từ cao đến thấp</a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div");

WriteLiteral(" class=\"row no-margin courses-result\"");

WriteLiteral(" id=\"courses-result\"");

WriteLiteral(">\r\n                        \r\n                    </div>\r\n                    <div" +
"");

WriteLiteral(" class=\"row no-margin courses-pagination paging-ctrl\"");

WriteLiteral(">\r\n                    </div>\r\n                </div>\r\n            </div>\r\n      " +
"  </div>\r\n    </main>\r\n</div>\r\n");

            
            #line 162 "..\..\Views\Category\Index.cshtml"
Write(Html.Partial("~/Views/Category/PartialView/_CousesResult.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 9464), Tuple.Create("\"", 9494)
, Tuple.Create(Tuple.Create("", 9470), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery.tmpl.js")
, 9470), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var categoryRouter = \'");

            
            #line 166 "..\..\Views\Category\Index.cshtml"
                         Write(Model.CategoryRouter);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    </script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 9625), Tuple.Create("\"", 9664)
, Tuple.Create(Tuple.Create("", 9631), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/bootstrap-pagination.js")
, 9631), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 9688), Tuple.Create("\"", 9729)
, Tuple.Create(Tuple.Create("", 9694), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/gds/gds.paging.control.js")
, 9694), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 9753), Tuple.Create("\"", 9788)
, Tuple.Create(Tuple.Create("", 9759), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/gds/gds.category.js")
, 9759), false)
);

WriteLiteral("></script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
